/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SimuladorRouteImport } from './routes/simulador'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as DesafiosRouteImport } from './routes/desafios'
import { Route as ComunidadeRouteImport } from './routes/comunidade'
import { Route as BemVindoRouteImport } from './routes/bem-vindo'
import { Route as AutoavaliacaoRouteImport } from './routes/autoavaliacao'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuiaPararDeApostarRouteImport } from './routes/guia.parar-de-apostar'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladorRoute = SimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafiosRoute = DesafiosRouteImport.update({
  id: '/desafios',
  path: '/desafios',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRoute = ComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const BemVindoRoute = BemVindoRouteImport.update({
  id: '/bem-vindo',
  path: '/bem-vindo',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoavaliacaoRoute = AutoavaliacaoRouteImport.update({
  id: '/autoavaliacao',
  path: '/autoavaliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaPararDeApostarRoute = GuiaPararDeApostarRouteImport.update({
  id: '/guia/parar-de-apostar',
  path: '/guia/parar-de-apostar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/autoavaliacao': typeof AutoavaliacaoRoute
  '/bem-vindo': typeof BemVindoRoute
  '/comunidade': typeof ComunidadeRoute
  '/desafios': typeof DesafiosRoute
  '/metas': typeof MetasRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/simulador': typeof SimuladorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/guia/parar-de-apostar': typeof GuiaPararDeApostarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/autoavaliacao': typeof AutoavaliacaoRoute
  '/bem-vindo': typeof BemVindoRoute
  '/comunidade': typeof ComunidadeRoute
  '/desafios': typeof DesafiosRoute
  '/metas': typeof MetasRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/simulador': typeof SimuladorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/guia/parar-de-apostar': typeof GuiaPararDeApostarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/autoavaliacao': typeof AutoavaliacaoRoute
  '/bem-vindo': typeof BemVindoRoute
  '/comunidade': typeof ComunidadeRoute
  '/desafios': typeof DesafiosRoute
  '/metas': typeof MetasRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/simulador': typeof SimuladorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/guia/parar-de-apostar': typeof GuiaPararDeApostarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/autoavaliacao'
    | '/bem-vindo'
    | '/comunidade'
    | '/desafios'
    | '/metas'
    | '/perfil'
    | '/privacidade'
    | '/simulador'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/guia/parar-de-apostar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/autoavaliacao'
    | '/bem-vindo'
    | '/comunidade'
    | '/desafios'
    | '/metas'
    | '/perfil'
    | '/privacidade'
    | '/simulador'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/guia/parar-de-apostar'
  id:
    | '__root__'
    | '/'
    | '/ajuda'
    | '/autoavaliacao'
    | '/bem-vindo'
    | '/comunidade'
    | '/desafios'
    | '/metas'
    | '/perfil'
    | '/privacidade'
    | '/simulador'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/guia/parar-de-apostar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjudaRoute: typeof AjudaRoute
  AutoavaliacaoRoute: typeof AutoavaliacaoRoute
  BemVindoRoute: typeof BemVindoRoute
  ComunidadeRoute: typeof ComunidadeRoute
  DesafiosRoute: typeof DesafiosRoute
  MetasRoute: typeof MetasRoute
  PerfilRoute: typeof PerfilRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SimuladorRoute: typeof SimuladorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  GuiaPararDeApostarRoute: typeof GuiaPararDeApostarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulador': {
      id: '/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof SimuladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafios': {
      id: '/desafios'
      path: '/desafios'
      fullPath: '/desafios'
      preLoaderRoute: typeof DesafiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade': {
      id: '/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof ComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bem-vindo': {
      id: '/bem-vindo'
      path: '/bem-vindo'
      fullPath: '/bem-vindo'
      preLoaderRoute: typeof BemVindoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoavaliacao': {
      id: '/autoavaliacao'
      path: '/autoavaliacao'
      fullPath: '/autoavaliacao'
      preLoaderRoute: typeof AutoavaliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia/parar-de-apostar': {
      id: '/guia/parar-de-apostar'
      path: '/guia/parar-de-apostar'
      fullPath: '/guia/parar-de-apostar'
      preLoaderRoute: typeof GuiaPararDeApostarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjudaRoute: AjudaRoute,
  AutoavaliacaoRoute: AutoavaliacaoRoute,
  BemVindoRoute: BemVindoRoute,
  ComunidadeRoute: ComunidadeRoute,
  DesafiosRoute: DesafiosRoute,
  MetasRoute: MetasRoute,
  PerfilRoute: PerfilRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SimuladorRoute: SimuladorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  GuiaPararDeApostarRoute: GuiaPararDeApostarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
