/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SimuladorRouteImport } from './routes/simulador'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as DesafiosRouteImport } from './routes/desafios'
import { Route as ComunidadeRouteImport } from './routes/comunidade'
import { Route as BemVindoRouteImport } from './routes/bem-vindo'
import { Route as AutoavaliacaoRouteImport } from './routes/autoavaliacao'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuiaPararDeApostarRouteImport } from './routes/guia.parar-de-apostar'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladorRoute = SimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafiosRoute = DesafiosRouteImport.update({
  id: '/desafios',
  path: '/desafios',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRoute = ComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const BemVindoRoute = BemVindoRouteImport.update({
  id: '/bem-vindo',
  path: '/bem-vindo',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoavaliacaoRoute = AutoavaliacaoRouteImport.update({
  id: '/autoavaliacao',
  path: '/autoavaliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaPararDeApostarRoute = GuiaPararDeApostarRouteImport.update({
  id: '/guia/parar-de-apostar',
  path: '/guia/parar-de-apostar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/autoavaliacao': typeof AutoavaliacaoRoute
  '/bem-vindo': typeof BemVindoRoute
  '/comunidade': typeof ComunidadeRoute
  '/desafios': typeof DesafiosRoute
  '/perfil': typeof PerfilRoute
  '/simulador': typeof SimuladorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guia/parar-de-apostar': typeof GuiaPararDeApostarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/autoavaliacao': typeof AutoavaliacaoRoute
  '/bem-vindo': typeof BemVindoRoute
  '/comunidade': typeof ComunidadeRoute
  '/desafios': typeof DesafiosRoute
  '/perfil': typeof PerfilRoute
  '/simulador': typeof SimuladorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guia/parar-de-apostar': typeof GuiaPararDeApostarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/autoavaliacao': typeof AutoavaliacaoRoute
  '/bem-vindo': typeof BemVindoRoute
  '/comunidade': typeof ComunidadeRoute
  '/desafios': typeof DesafiosRoute
  '/perfil': typeof PerfilRoute
  '/simulador': typeof SimuladorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guia/parar-de-apostar': typeof GuiaPararDeApostarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/autoavaliacao'
    | '/bem-vindo'
    | '/comunidade'
    | '/desafios'
    | '/perfil'
    | '/simulador'
    | '/sitemap.xml'
    | '/guia/parar-de-apostar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/autoavaliacao'
    | '/bem-vindo'
    | '/comunidade'
    | '/desafios'
    | '/perfil'
    | '/simulador'
    | '/sitemap.xml'
    | '/guia/parar-de-apostar'
  id:
    | '__root__'
    | '/'
    | '/ajuda'
    | '/autoavaliacao'
    | '/bem-vindo'
    | '/comunidade'
    | '/desafios'
    | '/perfil'
    | '/simulador'
    | '/sitemap.xml'
    | '/guia/parar-de-apostar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjudaRoute: typeof AjudaRoute
  AutoavaliacaoRoute: typeof AutoavaliacaoRoute
  BemVindoRoute: typeof BemVindoRoute
  ComunidadeRoute: typeof ComunidadeRoute
  DesafiosRoute: typeof DesafiosRoute
  PerfilRoute: typeof PerfilRoute
  SimuladorRoute: typeof SimuladorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GuiaPararDeApostarRoute: typeof GuiaPararDeApostarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulador': {
      id: '/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof SimuladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafios': {
      id: '/desafios'
      path: '/desafios'
      fullPath: '/desafios'
      preLoaderRoute: typeof DesafiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade': {
      id: '/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof ComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bem-vindo': {
      id: '/bem-vindo'
      path: '/bem-vindo'
      fullPath: '/bem-vindo'
      preLoaderRoute: typeof BemVindoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoavaliacao': {
      id: '/autoavaliacao'
      path: '/autoavaliacao'
      fullPath: '/autoavaliacao'
      preLoaderRoute: typeof AutoavaliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia/parar-de-apostar': {
      id: '/guia/parar-de-apostar'
      path: '/guia/parar-de-apostar'
      fullPath: '/guia/parar-de-apostar'
      preLoaderRoute: typeof GuiaPararDeApostarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjudaRoute: AjudaRoute,
  AutoavaliacaoRoute: AutoavaliacaoRoute,
  BemVindoRoute: BemVindoRoute,
  ComunidadeRoute: ComunidadeRoute,
  DesafiosRoute: DesafiosRoute,
  PerfilRoute: PerfilRoute,
  SimuladorRoute: SimuladorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GuiaPararDeApostarRoute: GuiaPararDeApostarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
